### ISSUE TITLE
video rendering issue

### ISSUE THREAD

**Issue by TofpFL** [JordanSantiagoYT/Mods-for-JS-Engine#10]
`[image2 @ 000001f82c6dc9c0] Could find no file with path './moai-wine/%07d.jpg' and index in the range 0-4./moai-wine/%07d.jpg: No such file or directory`

when i put the video up, it didnt match song length, and at specific point the renderer shat itself and made this werid static thing

**Comment by JordanSantiagoYT** [comment]
> `[image2 @ 000001f82c6dc9c0] Could find no file with path './moai-wine/%07d.jpg' and index in the range 0-4./moai-wine/%07d.jpg: No such file or directory`
> 
> when i put the video up, it didnt match song length, and at specific point the renderer shat itself and made this werid static thing
..why are you using the old video renderer..?

**Comment by FazeBWD** [comment]
its legit the same software is there an update?

**Comment by JordanSantiagoYT** [comment]
> its legit the same software is there an update?
1.22.0 removed the old video renderer for a new and better one 😭

**Comment by FazeBWD** [comment]
WELL THEN HOW TF DO I GET THE NEW SOFTWARE D:
________________________________

**Comment by FazeBWD** [comment]
How do I get new video renderer thing is it same FFMpeg but different version?

**Comment by JordanSantiagoYT** [comment]
> How do I get new video renderer thing is it same FFMpeg but different version?

1. Update to 1.23.0
2. Download [ffmpeg](https://github.com/BtbN/FFmpeg-Builds/releases)
3. Put ffmpeg.exe in the same directory as JSEngine.exe
4. DO NOT delete gameRenders or it won't work!
