### ISSUE TITLE
CRASH????

### ISSUE THREAD

**Issue by sigma993240** [JordanSantiagoYT/Mods-for-JS-Engine#11]
splitation 2 dosent load
https://github.com/JordanSantiagoYT/Mods-for-JS-Engine/assets/170710933/10bad9ad-9562-40ec-bd34-e76eb418a097
my version: newest
my settings:https://github.com/JordanSantiagoYT/Mods-for-JS-Engine/assets/170710933/91c2e6a0-89b5-4b91-af60-92c4310f4e7a

**Comment by JordanSantiagoYT** [comment]
note splash-related bug, gonna fix that

**Comment by JordanSantiagoYT** [comment]
Fixed in latest download
