### ISSUE TITLE
make the funnysongs folder downloadable man

### ISSUE THREAD

**Issue by nikitabaev71** [JordanSantiagoYT/Mods-for-JS-Engine#13]
plz

**Comment by NAEL2XD** [comment]
use git
then in search bar type cmd, when it is popped up, type: git clone https://github.com/JordanSantiagoYT/Mods-for-JS-Engine.git

**Comment by cyklusiguess** [comment]
> use git then in search bar type cmd, when it is popped up, type: git clone https://github.com/JordanSantiagoYT/Mods-for-JS-Engine.git

he meant funnysongs, not the entire repo with all mods folder

**Comment by NAEL2XD** [comment]
> > use git then in search bar type cmd, when it is popped up, type: git clone https://github.com/JordanSantiagoYT/Mods-for-JS-Engine.git
> 
> he meant funnysongs, not the entire repo with all mods folder

wouldn't it also contain the mod?

**Comment by nikitabaev71** [comment]
so i mean that funnysongs folder needs to be downloadable in the Separate Mod Downloads

**Comment by JordanSantiagoYT** [comment]
the thing is.. that folder is updated daily

**Comment by nikitabaev71** [comment]
and also jordan, why dont u update short songs folder in the Separate Mod Downloads?
