### ISSUE TITLE
how to use trigger scared bf?

### ISSUE THREAD

**Issue by helpmesd** [JordanSantiagoYT/Mods-for-JS-Engine#14]
how to use trigger scared bf?

**Comment by JordanSantiagoYT** [comment]
Chart Editor

go to the events menu, then the events dropdown. find an event called "Trigger Scared BF".
it has 4 variants: bfScared (0), bfMildScared (1), bfVeryScared (2), bfTraumatized (3), bf (4)

if you want to import it into your mod, you'll have to import all the additional character files for the bf variants, as well as the character images

**Comment by helpmesd** [comment]
i have new problem i have 2x more notes what doing?
