### ISSUE TITLE
Don't use buzzheavier for the Funnysongs final release

### ISSUE THREAD

**Issue by TheKamboy** [JordanSantiagoYT/Mods-for-JS-Engine#17]
It has been discovered that buzzheavier uses a fishy way of showing ads, by detecting if an ad has been hidden (by ad block) and makes it so that when you click the download button, it redirects you to an ad, which had caused someone who used buzzheavier to get a fake download ad, and they got hacked.

Link to a video about it: https://www.youtube.com/watch?v=qGh5JzLfljM

**Comment by acc0untz0138** [comment]
me when ublock origin, ubo lite, etc (they stop the redirects that happen):

**Comment by TheKamboy** [comment]
> me when ublock origin, ubo lite, etc (they stop the redirects that happen):

If you need AdBlock to not get a virus by a website, is it a good website? No it isn't.

**Comment by acc0untz0138** [comment]
my brother in christ
if you dont have an adblocker in 2024 idek what to say 😭

**Comment by JordanSantiagoYT** [comment]
hi!! i appreciate your concern however i can't put it anywhere else because..

I do not have enough storage to put the zip on Google Drive.
![image](https://github.com/user-attachments/assets/94b132fe-5717-457f-a58b-381713fa3bfa)

**Comment by JordanSantiagoYT** [comment]
nvm mega is another option i just don't have access to it in ME

![image](https://github.com/user-attachments/assets/991e26b7-a4fc-473c-bd3a-f3a09d9b77c9)

**Comment by JordanSantiagoYT** [comment]
check the release :)
