### ISSUE TITLE
I keep getting a error everytime i load a song

### ISSUE THREAD

**Issue by ScrumptiousBrownie** [JordanSantiagoYT/Mods-for-JS-Engine#2]
![Friday Night Funkin'_ Psych Engine 9_24_2023 11_55_21 AM](https://github.com/JordanSantiagoYT/Mods-for-JS-Engine/assets/132102005/8e9035bf-2faf-4d41-807e-a6647f1793b2)
everytime i load a song this error appears why does it do this?

**Comment by JordanSantiagoYT** [comment]
1. report the issues in https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/issues please!!
2. lua extra keys songs don't work with custom note skins, so change the note style to default if you're trying to load an extra keys song

**Comment by ScrumptiousBrownie** [comment]
k but im not using extra key songs i have no mods and it just wont stop crashing
