### ISSUE TITLE
Turning on botplay

### ISSUE THREAD

**Issue by Zalkeyz** [JordanSantiagoYT/Mods-for-JS-Engine#4]
whenever I want to turn on botplay mode the game crashes and it says null object refrence. I have the latest version of JS engine and I don't know whats happening..

**Comment by JordanSantiagoYT** [comment]
yeah, i forgot to make it so that toggling the botplay in pause menu doesnt interact with the botplaytxt in playstate if you arent on botplay because the text is ONLY created if you have botplay turned on before entering the song

**Comment by Zalkeyz** [comment]
Is there any way I can fix this? If it involves source code I can't do that because I'm having trouble compiling the .exe file when going into export/bin/...

**Comment by JordanSantiagoYT** [comment]
it does involve source code but i should already have it fixed, check the JS Engine action builds :3

**Comment by JordanSantiagoYT** [comment]
btw, they’re in the NoBotplayLag source

**Comment by Zalkeyz** [comment]
what version is it. Did you recently release it?

**Comment by JordanSantiagoYT** [comment]
it’s this: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions/runs/6526174687

**Comment by Zalkeyz** [comment]
Just to confirm, this explains how to compile the source code correctly?

**Comment by Zalkeyz** [comment]
if so I could try

**Comment by JordanSantiagoYT** [comment]
no, the action build is just a compiled build of the latest change in the repository

**Comment by Zalkeyz** [comment]
ok thank you
