### ISSUE TITLE
Archive is damaged

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/Mods-for-JS-Engine#5]
Says the archive is damaged, I can’t extract the archive

**Comment by JordanSantiagoYT** [comment]
where did you download the zip from

**Comment by JordanSantiagoYT** [comment]
ive tried opening this with both window explorer and winrar, neither of them said the zip was invalid or damaged.

did you try downloading it from here?
![image](https://github.com/JordanSantiagoYT/Mods-for-JS-Engine/assets/61796448/704601c5-414c-4989-9a5f-f4cb9f82df29)

**Comment by bimbifan** [comment]
Sorry for not answering for a long time, I downloaded it from here as always

**Comment by bimbifan** [comment]
I understood how this bug happens. It all depends on my download speed
