### ISSUE TITLE
The Updater of the Engine is broken

### ISSUE THREAD

**Issue by radishYT** [JordanSantiagoYT/Mods-for-JS-Engine#8]
I installed the 1.19.1 update here, unzipped it, starting it, and then it says: Your JS Engine is outdated! v1.19.0 < v1.19.1.
![Screenshot 2024-02-05 181812](https://github.com/JordanSantiagoYT/Mods-for-JS-Engine/assets/146760432/bc3ed55a-d53e-4a26-a72d-176e19244c3d)

**Comment by NAEL2XD** [comment]
new version were released so go to releases
