### ISSUE TITLE
Would like to know the size of zip for future users to Access 

### ISSUE THREAD

**Issue by Leon-Wolfren** [JordanSantiagoYT/Mods-for-JS-Engine#9]
Would it be possible to be able to get a file size listed for the mods zip as it shows up as unknown when downloading
Thanks

**Comment by JordanSantiagoYT** [comment]
~2.2GB

**Comment by JordanSantiagoYT** [comment]
But it's ~3.6 GB unzipped

**Comment by Leon-Wolfren** [comment]
Thank you... Suggest leaving this thread for future use

**Comment by JordanSantiagoYT** [comment]
Ok

**Comment by Leon-Wolfren** [comment]
Readme says
"The source code should come with a "Quick SETUP" batch file. Run it in order to install all the needed libraries for JS Engine!"
Quick setup ended with: haxelib --never list *shows list* you may now compile JS engine!
But now what... I have no idea what to do now...
Is there a tutorial for opening and running this because I cannot find a .exe file anywhere.
A Tutorial would be great for this on the readme because I do not know how to code or where to go next
Thank you for your time

**Comment by JordanSantiagoYT** [comment]
> Readme says "The source code should come with a "Quick SETUP" batch file. Run it in order to install all the needed libraries for JS Engine!" Quick setup ended with: haxelib --never list _shows following table of items_ you may now compile JS engine! But now what... I have no idea what to do now... Is there a tutorial for opening and running this because I cannot find a .exe file anywhere. A Tutorial would be great for this on the readme because I do not know how to code or where to go next Thank you for your time

are you serious?

just go into the art folder in your source code and run build_x64

**Comment by Leon-Wolfren** [comment]
Tried that, it failed to proceed I will show you the error log tomorrow morning

**Comment by JordanSantiagoYT** [comment]
> ![Screenshot (727)](https://private-user-images.githubusercontent.com/106228994/319779657-decb568a-99eb-4751-9aaf-1851de6e1bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjcwMzYsIm5iZiI6MTcxMjYyNjczNiwicGF0aCI6Ii8xMDYyMjg5OTQvMzE5Nzc5NjU3LWRlY2I1NjhhLTk5ZWItNDc1MS05YWFmLTE4NTFkZTZlMWJjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMTM4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWI2MzMxNTU5OTA0NjE0YjEyZmQ3YmJhYjUzNjdmYjc3NWQyNjcxYjc4YWU4OTYxNzBjMjQ2MmQ0YmRiMjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uur3Kx6I5IPPuMwSG2jdGjJlalzWNoZp8bSiLsu-SFo) ...I don't know what to do to fix this I don't use code or play around with source so I ain't touching shit without help Thank you

I can't help you with this. Especially since you're working with the rewrite.

**Comment by JordanSantiagoYT** [comment]
Alright, I checked. This can be caused by... you trying to compile without even having MSVC installed..

**Comment by Leon-Wolfren** [comment]
That's very funny because I have every single Microsoft visual C++

**Comment by Leon-Wolfren** [comment]
Got exactly the same warning as before nothing changed on build x64 or build x64 debug
It's not the msvc it can't be cause it's brand new

**Comment by JordanSantiagoYT** [comment]
What MSVC version are you using?

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/Mods-for-JS-Engine/assets/61796448/dabd50dd-d06a-4c57-905b-ce89b8d93c3d)
To also confirm, do you have these same options ticked?

**Comment by Leon-Wolfren** [comment]
> What MSVC version are you using?

The newest version both x64 and x86

**Comment by Leon-Wolfren** [comment]
> ![image](https://private-user-images.githubusercontent.com/61796448/320704804-dabd50dd-d06a-4c57-905b-ce89b8d93c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzEwMTUsIm5iZiI6MTcxMjYzMDcxNSwicGF0aCI6Ii82MTc5NjQ0OC8zMjA3MDQ4MDQtZGFiZDUwZGQtZDA2YS00YzU3LTkwNWItY2U4OWI4ZDkzYzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAyNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOWQ5MzY5ZDQ5MWMxZmYwZGI0NDRmODA4MGQ1YWIwNmFkMTU4ZjA4OGRiNjNiNzUwZGExOGM1NGQ0YTM4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cggvXpS4MceNS5nytMQrqPOn5t109wDD1XNub9C3ggY) To also confirm, do you have these same options ticked?



> ![image](https://private-user-images.githubusercontent.com/61796448/320704804-dabd50dd-d06a-4c57-905b-ce89b8d93c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzEwMTUsIm5iZiI6MTcxMjYzMDcxNSwicGF0aCI6Ii82MTc5NjQ0OC8zMjA3MDQ4MDQtZGFiZDUwZGQtZDA2YS00YzU3LTkwNWItY2U4OWI4ZDkzYzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAyNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOWQ5MzY5ZDQ5MWMxZmYwZGI0NDRmODA4MGQ1YWIwNmFkMTU4ZjA4OGRiNjNiNzUwZGExOGM1NGQ0YTM4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cggvXpS4MceNS5nytMQrqPOn5t109wDD1XNub9C3ggY) To also confirm, do you have these same options ticked?

First of all how did you access that menu?

**Comment by Leon-Wolfren** [comment]
Visual studio 6gb?!?! Nah I ain't installing bloatware on my PC 
Keep this thread open for other users I'm going to forget all about this
Until you make a working .exe sample without the need for visual I ain't touching this

**Comment by JordanSantiagoYT** [comment]
> Visual studio 6gb?!?! Nah I ain't installing bloatware on my PC Keep this thread open for other users I'm going to forget all about this Until you make a working .exe sample without the need for visual I ain't touching this

Alright, have fun not being able to compile your engine cause making an exe to compile your source code is impossible.

**Comment by Leon-Wolfren** [comment]
> > Visual studio 6gb?!?! Nah I ain't installing bloatware on my PC Keep this thread open for other users I'm going to forget all about this Until you make a working .exe sample without the need for visual I ain't touching this
> 
> Alright, have fun not being able to compile your engine cause making an exe to compile your source code is impossible.

I just lost interest anyway good luck with your engine

**Comment by Bernardof777** [comment]
Whats size

**Comment by StinkTheStinker** [comment]
> I just lost interest anyway good luck with your engine

i know this is an old issue, but did you use the latest version of flixel? if so, change to version 5.6.2 to see if that works.

**Comment by JordanSantiagoYT** [comment]
closing this because it is inactive, and the new repo size in readme.md solves this

**Comment by felipe881** [comment]
cool mods

**Comment by Scopomania** [comment]
I wish chrome doesn't failed it for my phone
